PetStoreProject/Areas/Admin/ViewModels/LoyalCustomerViewModel.cs
namespace PetStoreProject.Areas.Admin.ViewModels
{
    public class LoyalCustomerViewModel
    {
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string PhoneNumber { get; set; }
        public string LoyalName { get; set; }
        public bool IsActive { get; set; }
    }
}

PetStoreProject/Areas/Employee/ViewModels/LoyalCustomerViewModel.cs
namespace PetStoreProject.Areas.Employee.ViewModels
{
    public class LoyalCustomerViewModel
    {
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string PhoneNumber { get; set; }
        public string LoyalName { get; set; }
    }
}

PetStoreProject/Areas/Admin/Controllers/LoyalCustomerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PetStoreProject.Areas.Admin.ViewModels;
using PetStoreProject.Models;
using X.PagedList;

namespace PetStoreProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class LoyalCustomerController : Controller
    {
        private readonly PetStoreDBContext _dbContext;

        public LoyalCustomerController(PetStoreDBContext petStoreDBContext)
        {
            _dbContext = petStoreDBContext;
        }
        public IActionResult Index(int? page, int? pageSize, string phone)
        {
            List<LoyalCustomerViewModel> listLC = GetListLoyalCustomers();

            if (page == null)
            {
                page = 1;
            }
            if (pageSize == null)
            {
                pageSize = 12;
            }
            if (phone != null)
            {
                listLC = listLC.Where(x => x.PhoneNumber == phone).ToList();
            }
            return View(listLC.ToPagedList((int)page, (int)pageSize));
        }

        public IActionResult Refresh()
        {
            var totalTransactions = _dbContext.Orders
                                    .Where(o => o.CustomerId != null)
                                    .GroupBy(o => o.CustomerId)
                                    .Select(g => new
                                    {
                                        CustomerId = g.Key,
                                        TotalAmount = g.Sum(o => o.TotalAmount)
                                    }).ToList();

            foreach (var transaction in totalTransactions)
            {
                Customer customer = _dbContext.Customers.FirstOrDefault(c => c.CustomerId == transaction.CustomerId);
                if (customer != null)
                {
                    customer.TotalAmountSpent = (decimal?)transaction.TotalAmount;
                    List<LoyaltyLevel> listL = _dbContext.LoyaltyLevels.ToList();
                    foreach (var level in listL)
                    {
                        if (level.MinTotalAmount < (decimal?)transaction.TotalAmount && level.MaxTotalAmount >= (decimal?)transaction.TotalAmount)
                        {
                            customer.LoyaltyLevelID = level.LevelID;
                        }
                    }
                }
            }
            _dbContext.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult UpdateStatus(int CustomerId)
        {
            var c = _dbContext.Customers.FirstOrDefault(c => c.CustomerId == CustomerId);
            if (c != null)
            {
                try
                {
                    c.isLoyalty = !c.isLoyalty;
                    _dbContext.SaveChanges();
                    return Ok(new
                    {
                        success = true,
                        message = "Cập nhật thành cônggggg"
                    });
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Error updating status: {ex.Message}");
                }
            }
            return BadRequest(new
            {
                success = false,
                message = "Cập nhật không thành công"
            });
        }

        public List<LoyalCustomerViewModel> GetListLoyalCustomers() => (from c in _dbContext.Customers
                                                                        join l in _dbContext.LoyaltyLevels on c.LoyaltyLevelID equals l.LevelID
                                                                        select new LoyalCustomerViewModel
                                                                        {
                                                                            CustomerId = c.CustomerId,
                                                                            CustomerName = c.FullName,
                                                                            PhoneNumber = c.Phone,
                                                                            LoyalName = l.LevelName,
                                                                            IsActive = (bool)c.isLoyalty,
                                                                        }).ToList();
    }
}

PetStoreProject/Areas/Employee/Controllers/LoyalCustomerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PetStoreProject.Areas.Employee.ViewModels;
using PetStoreProject.Models;
using X.PagedList;


namespace PetStoreProject.Areas.Employee.Controllers
{
    [Area("Employee")]
    public class LoyalCustomerController : Controller
    {
        private readonly PetStoreDBContext _dbContext;
        public LoyalCustomerController(PetStoreDBContext petStoreDBContext)
        {
            _dbContext = petStoreDBContext;
        }
        public IActionResult Index(int? page, int? pageSize, string phone)
        {
            List<LoyalCustomerViewModel> listLC = GetListLoyalCustomers();

            if (page == null)
            {
                page = 1;
            }
            if (pageSize == null)
            {
                pageSize = 12;
            }
            if(phone != null)
            {
                listLC = listLC.Where(x => x.PhoneNumber == phone).ToList();
            }
            return View(listLC.ToPagedList((int)page, (int)pageSize));
        }

        public IActionResult Refresh()
        {
            var totalTransactions = _dbContext.Orders
                                    .Where(o => o.CustomerId != null)
                                    .GroupBy(o => o.CustomerId)
                                    .Select(g => new
                                    {
                                        CustomerId = g.Key,
                                        TotalAmount = g.Sum(o => o.TotalAmount)
                                    }).ToList();

            foreach (var transaction in totalTransactions)
            {
                Customer customer = _dbContext.Customers.FirstOrDefault(c => c.CustomerId == transaction.CustomerId);
                if (customer != null)
                {
                    customer.TotalAmountSpent = (decimal?)transaction.TotalAmount;
                    List<LoyaltyLevel> listL = _dbContext.LoyaltyLevels.ToList();
                    foreach (var level in listL)
                    {
                        if (level.MinTotalAmount < (decimal?)transaction.TotalAmount && level.MaxTotalAmount >= (decimal?)transaction.TotalAmount)
                        {
                            customer.LoyaltyLevelID = level.LevelID;
                        }
                    }
                }
            }
            _dbContext.SaveChanges();
            return RedirectToAction("Index");
        }

        public List<LoyalCustomerViewModel> GetListLoyalCustomers() => (from c in _dbContext.Customers
                                                                        join l in _dbContext.LoyaltyLevels on c.LoyaltyLevelID equals l.LevelID
                                                                        where c.isLoyalty == true
                                                                        select new LoyalCustomerViewModel
                                                                        {
                                                                            CustomerId = c.CustomerId,
                                                                            CustomerName = c.FullName,
                                                                            PhoneNumber = c.Phone,
                                                                            LoyalName = l.LevelName,
                                                                        }).ToList();
    }
}

PetStoreProject/Areas/Employee/Views/LoyalCustomer/Index.cshtml
@using X.PagedList.Mvc.Core
@using X.PagedList
@model IPagedList<PetStoreProject.Areas.Employee.ViewModels.LoyalCustomerViewModel>


<style>
    .pagination-blog {
        display: flex;
        justify-content: center;
        margin-top: 20px;
        .pagination

    {
        display: flex;
        list-style: none;
        padding: 0;
        margin: 0;
        justify-content: center;
    }

    .pagination li {
        margin: 0 5px;
    }

    .pagination a, .pagination span {
        color: #007bff;
        text-decoration: none;
        border: 1px solid #dee2e6;
        padding: 8px 12px;
        border-radius: 4px;
        transition: background-color 0.3s;
    }

        .pagination a:hover {
            background-color: #e9ecef;
        }

    .pagination .active span {
        background-color: #007bff;
        color: white;
        border-color: #007bff;
    }
</style>


<div class="main-content-inner">
    <!-- main-content-wrap -->
    <div class="main-content-wrap">
        <div class="flex items-center flex-wrap justify-between gap20 mb-27">
            <h3>Danh sách khách hàng thân thiết</h3>
            <ul class="breadcrumbs flex items-center flex-wrap justify-start gap10">
                <li>
                    <a href="index.html"><div class="text-tiny">Bảng điều khiển</div></a>
                </li>
                <li>
                    <i class="icon-chevron-right"></i>
                </li>
                <li>
                    <a href="#"><div class="text-tiny">Khách hàng thân thiết</div></a>
                </li>
                <li>
                    <i class="icon-chevron-right"></i>
                </li>
                <li>
                    <div class="text-tiny">Danh sách khách hàng thân thiết</div>
                </li>
            </ul>
        </div>
        <!-- all-roles -->
        <div class="wg-box">
            <div class="flex items-center justify-between gap10 flex-wrap">
                <div class="wg-filter flex-grow">
                    <form class="form-search" asp-action="Index" asp-controller="LoyalCustomer" method="get">
                        <fieldset class="name">
                            <input type="text" placeholder="Tìm kiếm theo số điện thoại..." class="" name="phone" tabindex="2" value="" aria-required="true" required="">
                        </fieldset>
                        <div class="button-submit">
                            <button class="" type="submit"><i class="icon-search"></i></button>
                        </div>
                    </form>
                </div>
                <a class="tf-button style-1 w208" asp-action="Refresh" asp-controller="LoyalCustomer"><i class="icon-refresh-cw"></i>Làm mới trang</a>
            </div>
            <div class="wg-table table-all-attribute">
                <ul class="table-title flex gap20 mb-14">
                    <li style="width: 4%;">
                        <div class="body-title">No.</div>
                    </li>
                    <li style="width: 32%;">
                        <div class="body-title">Tên khách hàng</div>
                    </li>
                    <li style="width: 32%;">
                        <div class="body-title">Số điện thoại</div>
                    </li>
                    <li style="width: 32%;">
                        <div class="body-title">Hạng thân thiết</div>
                    </li>
                </ul>
                <ul class="flex flex-column">
                    @foreach (var item in Model)
                    {
                        <li class="attribute-item flex items-center justify-between gap20">
                            <div class="body-text" style="width: 4%; word-wrap: break-word;">@item.CustomerId</div>
                            <div class="body-text" style="width: 32%; word-wrap: break-word;">@item.CustomerName</div>
                            <div class="body-text" style="width: 32%; word-wrap: break-word;">@item.PhoneNumber</div>
                            <div class="body-text" style="width: 32%; word-wrap: break-word;">@item.LoyalName</div>
                        </li>
                    }
                </ul>
            </div>
            <div class="pagination-blog">
                @Html.PagedListPager(Model, page => Url.Action("ListNews", new { page, pagesize = 12 }))
            </div>
        </div>
        
    </div>
    
    <!-- /main-content-wrap -->
</div>